trigger:
  - master

resources:
  containers:
    - container: centos7
      image: yugabyteci/yb_build_infra_centos7:v2020-03-28T07_29_17
      options: "--cap-add=SYS_PTRACE"

jobs:
  - job: RunInContainer
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 0

    strategy:
      matrix:
        centos7:
          containerResource: centos7

    container: $[ variables['containerResource'] ]

    steps:
      - script: |
          sudo mkdir -p /opt/yb-build
          sudo chown yugabyteci /opt/yb-build
          sudo mkdir -p /opt/yb-build/thirdparty
          sudo chown yugabyteci /opt/yb-build/thirdparty
          checkout_dir=$PWD
          chmod -R a+r "$checkout_dir"
          find "$checkout_dir" -executable -type f -exec chmod a+x {} \;
          sudo -u yugabyteci -E /bin/bash -c \
            "cd '$checkout_dir' && YB_MAKE_PARALLELISM=1 ./build_and_release.sh"
        env:
          GITHUB_TOKEN: $(yugabyte.githubToken)
