trigger:
  - master

resources:
  containers:
    - container: ubuntu1804
      image: yugabytedb/yb_build_infra_ubuntu1804:v2019-04-30T20_16_36_mikhail
      options: "--cap-add=SYS_PTRACE"

    - container: ubuntu1904_gcc7
      image: yugabytedb/yb_build_infra_ubuntu1904_gcc7:v2019-07-12T01_07_36_mbautin
      options: "--cap-add=SYS_PTRACE"

    - container: centos7
      image: yugabytedb/yb_build_infra_centos7:v2019-04-30T20_16_52_mikhail
      options: "--cap-add=SYS_PTRACE"

jobs:
  - job: RunInContainer
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 0

    strategy:
      matrix:
        ubuntu1804:
          containerResource: ubuntu1804
        centos7:
          containerResource: centos7
        ubuntu1904_gcc7:
          containerResource: ubuntu1904_gcc7

    container: $[ variables['containerResource'] ]

    steps:
      - script: ./build_and_release.sh
        env:
          GITHUB_TOKEN: $(yugabyte.githubToken)
